### ISSUE TITLE
ESPHome 2023.12.9 "Component inaccessible due to ambiguity"

### ISSUE THREAD

**Issue by ronnieSVK** [latonita/esphome-st7567s-display#1]
Dear Developer !

Since i would like to Test and find out to most suitable display for specific project, i went to "troubles" wih upper mentioned ST7567s models, due to lack of support in ESPHome. Im using most recent 2023.12.9 PROD version, and during compiling ill get following errors (please see below). Do we have please the option to solve it, or i have to wait for official release where should be regarding to your words this component included ?

Thank you very much !

`HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/esphome-web-95f614/src/esphome/components/st7567s/st7567s.cpp.o
Compiling .pioenvs/esphome-web-95f614/src/main.cpp.o
In file included from src/esphome/components/st7567s/st7567s.cpp:1:
src/esphome/components/st7567s/st7567s.h:15:7: warning: direct base 'esphome::PollingComponent' inaccessible in 'esphome::st7567s::ST7567S' due to ambiguity
 class ST7567S : public PollingComponent, public display::DisplayBuffer, public i2c::I2CDevice {
       ^~~~~~~
src/esphome/components/st7567s/st7567s.cpp: In member function 'virtual void esphome::st7567s::ST7567S::setup()':
src/esphome/components/st7567s/st7567s.cpp:58:15: error: request for member 'mark_failed' is ambiguous
         this->mark_failed();
               ^~~~~~~~~~~
In file included from src/esphome/core/color.h:3,
                 from src/esphome/components/display/display.h:8,
                 from src/esphome/components/display/display_buffer.h:6,
                 from src/esphome/components/st7567s/st7567s.h:3,
                 from src/esphome/components/st7567s/st7567s.cpp:1:
src/esphome/core/component.h:118:16: note: candidates are: 'virtual void esphome::Component::mark_failed()'
   virtual void mark_failed();
                ^~~~~~~~~~~
src/esphome/core/component.h:118:16: note:                 'virtual void esphome::Component::mark_failed()'
src/esphome/components/st7567s/st7567s.cpp: In member function 'virtual void esphome::st7567s::ST7567S::dump_config()':
src/esphome/core/component.h:47:13: error: request for member 'get_update_interval' is ambiguous
   if (this->get_update_interval() == SCHEDULER_DONT_RUN) { \
             ^~~~~~~~~~~~~~~~~~~
src/esphome/components/st7567s/st7567s.cpp:72:5: note: in expansion of macro 'LOG_UPDATE_INTERVAL'
     LOG_UPDATE_INTERVAL(this);
     ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note: candidates are: 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
   virtual uint32_t get_update_interval() const;
                    ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note:                 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
src/esphome/core/component.h:49:20: error: request for member 'get_update_interval' is ambiguous
   } else if (this->get_update_interval() < 100) { \
                    ^~~~~~~~~~~~~~~~~~~
src/esphome/components/st7567s/st7567s.cpp:72:5: note: in expansion of macro 'LOG_UPDATE_INTERVAL'
     LOG_UPDATE_INTERVAL(this);
     ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note: candidates are: 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
   virtual uint32_t get_update_interval() const;
                    ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note:                 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
In file included from src/esphome/components/sensor/sensor.h:3,
                 from src/esphome/core/application.h:16,
                 from src/esphome/components/st7567s/st7567s.cpp:3:
src/esphome/core/component.h:50:58: error: request for member 'get_update_interval' is ambiguous
     ESP_LOGCONFIG(TAG, "  Update Interval: %.3fs", this->get_update_interval() / 1000.0f); \
                                                          ^~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^~~~~~~~~~~
src/esphome/core/component.h:50:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "  Update Interval: %.3fs", this->get_update_interval() / 1000.0f); \
     ^~~~~~~~~~~~~
src/esphome/components/st7567s/st7567s.cpp:72:5: note: in expansion of macro 'LOG_UPDATE_INTERVAL'
     LOG_UPDATE_INTERVAL(this);
     ^~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/color.h:3,
                 from src/esphome/components/display/display.h:8,
                 from src/esphome/components/display/display_buffer.h:6,
                 from src/esphome/components/st7567s/st7567s.h:3,
                 from src/esphome/components/st7567s/st7567s.cpp:1:
src/esphome/core/component.h:309:20: note: candidates are: 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
   virtual uint32_t get_update_interval() const;
                    ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note:                 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
In file included from src/esphome/components/sensor/sensor.h:3,
                 from src/esphome/core/application.h:16,
                 from src/esphome/components/st7567s/st7567s.cpp:3:
src/esphome/core/component.h:52:58: error: request for member 'get_update_interval' is ambiguous
     ESP_LOGCONFIG(TAG, "  Update Interval: %.1fs", this->get_update_interval() / 1000.0f); \
                                                          ^~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^~~~~~~~~~~
src/esphome/core/component.h:52:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "  Update Interval: %.1fs", this->get_update_interval() / 1000.0f); \
     ^~~~~~~~~~~~~
src/esphome/components/st7567s/st7567s.cpp:72:5: note: in expansion of macro 'LOG_UPDATE_INTERVAL'
     LOG_UPDATE_INTERVAL(this);
     ^~~~~~~~~~~~~~~~~~~
In file included from src/esphome/core/color.h:3,
                 from src/esphome/components/display/display.h:8,
                 from src/esphome/components/display/display_buffer.h:6,
                 from src/esphome/components/st7567s/st7567s.h:3,
                 from src/esphome/components/st7567s/st7567s.cpp:1:
src/esphome/core/component.h:309:20: note: candidates are: 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
   virtual uint32_t get_update_interval() const;
                    ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:309:20: note:                 'virtual uint32_t esphome::PollingComponent::get_update_interval() const'
*** [.pioenvs/esphome-web-95f614/src/esphome/components/st7567s/st7567s.cpp.o] Error 1
In file included from src/esphome.h:59,
                 from src/main.cpp:3:
src/esphome/components/st7567s/st7567s.h:15:7: warning: direct base 'esphome::PollingComponent' inaccessible in 'esphome::st7567s::ST7567S' due to ambiguity
 class ST7567S : public PollingComponent, public display::DisplayBuffer, public i2c::I2CDevice {
       ^~~~~~~
<unicode string>: In function 'void setup()':
<unicode string>:121:23: error: request for member 'set_update_interval' is ambiguous
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/component.h:298:16: note: candidates are: 'virtual void esphome::PollingComponent::set_update_interval(uint32_t)'
   virtual void set_update_interval(uint32_t update_interval);
                ^~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:298:16: note:                 'virtual void esphome::PollingComponent::set_update_interval(uint32_t)'
<unicode string>:122:23: error: request for member 'set_component_source' is ambiguous
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/component.h:148:8: note: candidates are: 'void esphome::Component::set_component_source(const char*)'
   void set_component_source(const char *source) { component_source_ = source; }
        ^~~~~~~~~~~~~~~~~~~~
src/esphome/core/component.h:148:8: note:                 'void esphome::Component::set_component_source(const char*)'
In file included from src/esphome/components/api/api_connection.h:7,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/application.h: In instantiation of 'C* esphome::Application::register_component(C*) [with C = esphome::st7567s::ST7567S]':
<unicode string>:123:44:   required from here
src/esphome/core/application.h:149:31: error: 'esphome::Component' is an ambiguous base of 'esphome::st7567s::ST7567S'
     this->register_component_((Component *) c);
                               ^~~~~~~~~~~~~~~
*** [.pioenvs/esphome-web-95f614/src/main.cpp.o] Error 1
========================== [FAILED] Took 6.31 seconds ==========================`

**Comment by latonita** [comment]
please share your config

**Comment by latonita** [comment]
this component might have been included into your esphome version, so please check if its there. remove `external_component` section

**Comment by ronnieSVK** [comment]
Thank you. Config here 👍 

`esphome:
  name: esphome-web-95f614
  friendly_name: ESP32 Test Board

external_components:
  source: github://latonita/esphome-st7567s-display@main
  components: [st7567s]
  
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "b1BUVx6kGwYXjO11xhnVW6Favs3OFnX5V86cNhIbaYg="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:

dallas:
  - pin: GPIO19
    update_interval: 5s

sensor:
  - platform: dallas
    address: 0xfc3c77e381c59e28
    name: "ESP32_Test_Board_Temperature"
    id: internal_temperature

switch:
  - platform: gpio
    pin: GPIO18
    id: internal_heating_relay
    name: "ESP32_Test_Board_Relay"
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO23
      mode:
        input: true
        pullup: true
    name: "ESP32_Test_Board_PIR"
    id: internal_pir
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: internal_pir
            then:
              - display.page.show: page2
            else:
              - display.page.show: page1
    
i2c:
   - sda: GPIO21
     scl: GPIO22
     scan: true
     frequency: 800kHz
     id: bus_1

font:
  - file: "gfonts://Calibri"
    id: calibri
    size: 15

display:
  - platform: st7567s
    i2c_id: bus_1
    id: internal_display
    address: 0x3F
    pages:
      - id: page3    
        lambda: |-          
      - id: page4    
        lambda: |-          
          it.printf(8, 3, id(calibri), "Temperature: %.0f°C", id(internal_temperature).state);`

**Comment by ronnieSVK** [comment]
> this component might have been included into your esphome version, so please check if its there. remove `external_component` section

Thank you for your reply !

Ive tested
- platform: st7567s
ill get "Platform not found" message sadly. Do you have maybe idea in which platform should be this display included ? I checked some changelogs for latest releases, but found nothing :(

**Comment by latonita** [comment]
apologies for confusion. it is in Development branch for some time already.

**Comment by ronnieSVK** [comment]
No need to apologies, thank you for your response ! But does it mean please, that i have to switch to deve, no change to use your code under Prod as custom component ? No workaround for that please ?

Thank you !

**Comment by latonita** [comment]
I will check later today with current public/non-dev brach

BR, Anton
________________________________

**Comment by latonita** [comment]
@ronnieSVK okkaay, i backported dev version to be compatible with current esphome release.
This repo is updated.

Quick way to happiness:
```
external_components:
  - source: github://latonita/esphome-st7567s-display@main
    components: [st7567_base, st7567_i2c]

i2c:
#...

display:
  - platform: st7567_i2c
    id: lcd
    address: 0x3f
    update_interval: 500ms
    lambda: |-
      it.line(0,0,10,0); it.line(0,0,0,10);
      it.line(127,63,117,63); it.line(127,63,127,53);

```

**Comment by latonita** [comment]
please check and report )

**Comment by ronnieSVK** [comment]
Dear Anton,

Thank you very much for your work, time and effort ! Your custom component works now also in Prod without any issues ! The code was immediately valid and the display working. Time to continue testing :)

Issue solved !

Thank you very much once again,

Greetings
Ronnie
